COLUMNS:
  date_of_job_post: object
  title: object
  job_location: object
  company_name: object
  job_link: object
  job_summary: object
  job_type: object
  job_qualifications: object
  job_description: object

TARGET_COLUMN:
    name: title
