# Root directory for all artifacts
artifacts_root: artifacts

data_ingestion:
  # Directory where data ingestion artifacts are stored
  root_dir: artifacts/data_ingestion
  # URL from which data will be downloaded
  source_URL: https://github.com/etietopabraham/storage/raw/main/jobs_data_simply_hired.csv.zip
  # Path to the local file where downloaded data will be saved
  local_data_file: artifacts/data_ingestion/jobs_data_simply_hired.csv.zip
  # Directory where the zipped data will be extracted
  unzip_dir: artifacts/data_ingestion
