artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/etietopabraham/storage/raw/main/jobs_data_simply_hired.csv.zip
  local_data_file: artifacts/data_ingestion/jobs_data_simply_hired.csv.zip
  unzip_dir: artifacts/data_ingestion
