# Root directory for all artifacts

artifacts_root: artifacts


# Configuration related to data ingestion
data_ingestion:

  # Directory where data ingestion artifacts are stored
  root_dir: artifacts/data_ingestion

  # URL from which data will be downloaded
  source_URL: https://github.com/etietopabraham/storage/raw/main/jobs_simply_hired.csv.zip
  

  # Path to the local file where downloaded data will be saved
  local_data_file: artifacts/data_ingestion/jobs_simply_hired.csv.zip

  # Directory where the zipped data will be extracted
  unzip_dir: artifacts/data_ingestion


# Configuration related to data validation.
data_validation:

  # Path to the root directory where data validation artifacts are stored.
  root_dir: artifacts/data_validation
  
  # Location of the validated data (in this case, a CSV file).
  validated_data_file: artifacts/data_validation/validated_jobs_data.csv
  
  # Location of the extracted data (in this case, a CSV file) that needs to be validated.
  unzip_data_dir: artifacts/data_ingestion/jobs_simply_hired.csv
  
  # Path to a status file used to track the progress or status of data validation.
  STATUS_FILE: artifacts/data_validation/status.txt



# Data Transformation Configuration
data_transformation:
  
  # Root directory where all data transformation artifacts will be stored.
  root_dir: artifacts/data_transformation
  
  # Path to the validated dataset that will be used as input for transformation.
  data_path: artifacts/data_validation/validated_jobs_data.csv


# Model Trainer Configuration
model_trainer:
  # Path to the root directory where model trainer artifacts are stored.
  root_dir: artifacts/model_trainer
  
  # Location of the training dataset (in this case, a CSV file).
  train_data_path: artifacts/data_transformation/train_data.csv
  
  # Location of the testing dataset (in this case, a CSV file).
  test_data_path: artifacts/data_transformation/test_data.csv
  
  # Name of the serialized trained model to be saved.
  model_name: model.joblib


# Model Evaluation Configuration
model_evaluation:
  # Root directory to store evaluation artifacts
  root_dir: artifacts/model_evaluation
  
  # Path to the test dataset (output from the data transformation stage)
  test_data_path: artifacts/data_transformation/test_data.csv
  
  # Path to the trained model (output from the model trainer stage)
  model_path: artifacts/model_trainer/model.joblib
  
  # File path to save computed evaluation metrics in JSON format
  metric_file_name: artifacts/model_evaluation/metrics.json

  # MLFlow URI
  mlflow_uri: https://dagshub.com/etietopabraham/pixi_hr.mlflow


